const dataModel = {
  users: [
    {
      uid: 'user_1239809u',
      email: 'werbel.ted@gmail.com',
      firstName: 'Ted',
      lastName: 'Werbel',
      registeredCourses: [{ cid: 'asdasdasd' }],
      subscriptions: [{ sid: 'sub_jk1h32kjh', iid: 'iid_asdasd123123', active: true }],
      roles: ['student', 'admin'],
    },
    {
      uid: 'user_12312d9u',
      email: 'stefan.reid@gmail.com',
      firstName: 'Reid',
      lastName: 'Stefan',
      registeredCourses: [{ cid: 'asdasdasd' }],
      subscriptions: [{ sid: 'sub_jk1h32kjh', iid: 'iid_asdasd123123', active: true }],
      roles: ['student', 'instructor'],
    },
  ],
  courses: [
    {
      cid: 'cid_108h312hkas',
      courseName: 'Ableton Live 10 Essentials',
      courseDescription: 'Reid Stefan teaches the fundamentals of Ableton Live 10',
      instructorName: 'Reid Stefan',
      instructorId: 'iid_asdasd123123',
      instructorSupportEmail: 'stefan.reid.support@gmail.com',
      trailer: 'https://dfkv75gx1ii0n.cloudfront.net/60slaunchpromo14/master.m3u8',
      lessonOrder: ['lesson_128sadh9098sadsdd', 'lesson_128sadh9098sadsdd'],
      lessons: [
        {
          lid: 'lesson_128sadh9098sadsdd',
          index: 1,
          lessonName: 'Interface and key shorcuts',
          lessonDescription: 'In this lesson, we will begin by learning about the interface',
          lessonNotes: 'Course notes would go here with support for paragraphs.',
          stream: 'https://dfkv75gx1ii0n.cloudfront.net/60slaunchpromo14/master.m3u8',
          links: [{ name: 'Preset Files', url: 'http://mediafire.com/12DHkas' }],
          comments: [
            {
              comid: 'com_asjd19ubas9b',
              message: 'Great intro!',
              dateCreated: 12389172,
              commenterName: 'Ted Werbel',
              commenterId: 'user_1239809u',
            },
          ],
        },
      ],
    },
  ],
  instructors: [
    {
      iid: 'iid_asdasd123123',
      firstName: 'Reid',
      lastName: 'Stefan',
      description: 'Award winning producer and grammy nominee',
      supportEmail: 'stefan.reid.support@gmail.com',
      subscribers: [
        {
          sid: 'sub_asdj198h98ahsd',
          subscriberId: 'user_ljn124sd912',
          subscriberName: 'Roy Wilson',
          active: true,
        },
      ],
      posts: [
        {
          pid: 'post_as123jhs8hs',
          title: '10 Secret Sound Design Techniques',
          description: 'Early-access to an upcoming video for all of my members',
          dateCreated: 12374092,
          type: 'video',
          url: 'https://www.youtube.com/asdjnk12j3',
          private: true,
          limited: true,
          tiers: [2, 3],
        },
        {
          pid: 'post_as1d12s8hs',
          title: 'Lofi DrumKit',
          description: 'Download this exclsuive sound pack here!',
          dateCreated: 12374092,
          type: 'link',
          url: 'https://www.mediafire.com/akshd9712hdyasd',
          private: true,
          limited: false,
          tiers: null,
        },
        {
          pid: 'post_as1jjgj12s',
          title: 'Quick Update and Thank You',
          description: 'Thanks for the support everyone! New video dropping tonight!!',
          dateCreated: 12374092,
          type: 'text',
          url: null,
          private: false,
          limited: false,
          tiers: null,
        },
      ],
    },
  ],
};
