const dataModel2 = {
  users: [
    {
      uid: 'user_1239809u',
      email: 'werbel.ted@gmail.com',
      firstName: 'Ted',
      lastName: 'Werbel',
      private: {
        stripeCustomerId: 'cus_EbaS729Ha8jfH',
        purchases: [
          { stripeProductId: 'pro_Hkah7gJJ8a', charge: 'ch_xxxxxx', productName: 'course_name' },
        ],
        subscriptions: [
          { stripeSubscriptionId: 'sub_jk1h32kjh', instructor: 'iid_asdasd123123', active: true },
        ],
      },
      roles: ['student', 'admin'],
    },
    {
      uid: 'user_12312d9u',
      email: 'stefan.reid@gmail.com',
      firstName: 'Reid',
      lastName: 'Stefan',
      private: {
        stripeCustomerId: 'cus_EbaS729Ha8jfH',
        purchases: [
          { stripeProductId: 'pro_Hkah7gJJ8a', charge: 'ch_xxxxxx', productName: 'course_name' },
        ],
        subscriptions: [
          { stripeSubscriptionId: 'sub_jk1h32kjh', instructor: 'iid_asdasd123123', active: true },
        ],
      },
      roles: ['student', 'instructor'],
    },
  ],
  courses: [
    {
      cid: 'cid_108h312hkas',
      courseName: 'Ableton Live 10 Essentials',
      courseDescription: 'Reid Stefan teaches the fundamentals of Ableton Live 10',
      instructorName: 'Reid Stefan',
      instructorId: 'iid_asdasd123123',
      instructorSupportEmail: 'stefan.reid.support@gmail.com',
      trailer: 'https://dfkv75gx1ii0n.cloudfront.net/60slaunchpromo14/master.m3u8',
      lessonOrder: ['lesson_128sadh9098sadsdd', 'lesson_128sadh9098sadsdd'],
      lessons: [
        {
          lid: 'lesson_128sadh9098sadsdd',
          index: 1,
          lessonName: 'Interface and key shorcuts',
          lessonDescription: 'In this lesson, we will begin by learning about the interface',
          lessonNotes: 'Course notes would go here with support for paragraphs.',
          stream: 'https://dfkv75gx1ii0n.cloudfront.net/60slaunchpromo14/master.m3u8',
          links: [{ name: 'Preset Files', url: 'http://mediafire.com/12DHkas' }],
          comments: [
            {
              comid: 'com_asjd19ubas9b',
              message: 'Great intro!',
              dateCreated: 12389172,
              commenterName: 'Ted Werbel',
              commenterId: 'user_1239809u',
            },
          ],
        },
      ],
    },
  ],
  instructors: [
    {
      iid: 'iid_asdasd123123',
      firstName: 'Reid',
      lastName: 'Stefan',
      description: 'Award winning producer and grammy nominee',
      supportEmail: 'stefan.reid.support@gmail.com',
      subscribers: [
        {
          sid: 'sub_asdj198h98ahsd',
          uid: 'user_ljn124sd912',
          firstName: 'Roy',
          lastName: 'Wilson',
          active: true,
        },
      ],
      posts: [
        {
          postid: 'post_as123jhs8hs',
          title: '10 Secret Sound Design Techniques',
          description: 'Early-access to an upcoming video for all of my members',
          dateCreated: 12374092,
          type: 'video',
          url: 'https://www.youtube.com/asdjnk12j3',
          private: true,
          limited: true,
          tiers: [2, 3],
        },
        {
          postid: 'post_as1d12s8hs',
          title: 'Lofi DrumKit',
          description: 'Download this exclsuive sound pack here!',
          dateCreated: 12374092,
          type: 'link',
          url: 'https://www.mediafire.com/akshd9712hdyasd',
          private: true,
          limited: false,
          tiers: null,
        },
        {
          postid: 'post_as1jjgj12s',
          title: 'Quick Update and Thank You',
          description: 'Thanks for the support everyone! New video dropping tonight!!',
          dateCreated: 12374092,
          type: 'text',
          url: null,
          private: false,
          limited: false,
          tiers: null,
        },
      ],
    },
  ],
};

// Version 2 data model (v2 is without instructor payouts and subscriptions)
const dataModel = {
  users: [
    ...{
      uid: 'user_1239809u',
      email: 'werbel.ted@gmail.com',
      firstName: 'Ted',
      lastName: 'Werbel',
      private: {
        stripe_customer_id: 'cus_EbaS729Ha8jfH',
        purchases: [
          { stripe_product_id: 'pro_Hkah7gJJ8a', charge: 'ch_xxxxxx', productName: 'course_name' },
        ],
        subscriptions: [{ stripeSubscriptionId: 'sub_jk1h32kjh', active: true }],
      },
      roles: ['student', 'admin'],
    },
  ],
  courses: [
    {
      course_id: 'course_197ga27d',
      stripe_product_id: 'prod_akjsd87k',
      url: '/courses/scott-storch-teaches-music-production',
      instructor_name: 'Scott Storch',
      tagline: 'Teaches Music Production',
      cover_image: 'https://IMAGE_URL',
      trailer_url: 'https://TRAILER_URL',
      thumbnail_image: 'https://THUMBNAIL_URL',
      viewer_cover_image: 'https://IMAGE_URL',
      bio_title: 'Experience the Lengend',
      bio_description: 'Description goes here...',
      bio_image: 'https://BIO_IMAGE_URL',
      genius_url: 'https://GENIUS_URL',
      facebook_url: 'https://FACEBOOK_URL',
      twitter_url: 'https://TWITTER_URL',
      reddit_url: 'https://REDDIT_URL',
      playlist: [
        ...{
          video_id: 'vid_as7gsd2',
          thumbnail: 'https://THUMBNAIL_URL',
          description: 'Description goes here...',
          comments: {
            comment_id: 'com_12908as',
            message: 'Check it out - http://soundcloud.com/tjw/234naaa',
            user_name: 'Ted Werbel',
            user_id: 'uid_23n98sdf',
            likes: 0,
          },
        },
      ],
      active: true,
    },
  ],
  // ONLY ACCCESIBLE BY FIREBASE ADMIN
  videos: [{ video_id: 'vid_as7gsd2', video_url: 'https://JWPLAYER_VIDEO_URL' }],
};

// MASTERCLASS.COM API RESPONSE EXAMPLE

/**
 * {
   "hits":[
      {
         "id":99,
         "class_name":"David Lynch Teaches Creativity And Film",
         "instructor":"David Lynch",
         "headline":"Teaches Creativity and Film",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2514/original/1552938967-Headshot.jpg?1552938967",
         "class slug":"david-lynch-teaches-creativity-and-film",
         "url":"/classes/david-lynch-teaches-creativity-and-film",
         "category":"Film & TV",
         "trailer_slug":null,
         "description":"An avant-garde figure in filmmaking, David Lynch introduced mainstream audiences to art-house films. Now the Oscar-nominated director of Mulholland Drive teaches his cross-disciplinary creative process. Learn how he catches ideas, translates them into a narrative, and moves beyond formulaic storytelling. Embrace the art life in David’s MasterClass and learn to test the boundaries of your own artistic expression in any medium.",
         "status":"available",
         "instructor_name":"David Lynch",
         "objectID":"99"
      },
      {
         "id":98,
         "class_name":"Timbaland Teaches Producing And Beatmaking",
         "instructor":"Timbaland",
         "headline":"Teaches Producing and Beatmaking",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2434/original/1550699428-Headshot.jpg?1550699428",
         "class slug":"timbaland-teaches-producing-and-beatmaking",
         "url":"/classes/timbaland-teaches-producing-and-beatmaking",
         "category":"Music & Entertainment",
         "trailer_slug":null,
         "description":"Grammy-winning music producer Timbaland takes you behind the boards to teach you his process for creating iconic tracks with artists like Jay-Z, Missy Elliott, Justin Timberlake, Beyoncé, and Aaliyah. In his first-ever online class, learn how to collaborate with vocalists, layer new tracks, and create hooks that stick. Step into Timbaland’s studio and learn from one of the industry’s most innovative hit makers.",
         "status":"available",
         "instructor_name":"Timbaland",
         "objectID":"98"
      },
      {
         "id":97,
         "class_name":"Neil Gaiman Teaches The Art Of Storytelling",
         "instructor":"Neil Gaiman",
         "headline":"Teaches the Art of Storytelling",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2412/original/1548462897-Headshot.jpg?1548462897",
         "class slug":"neil-gaiman-teaches-the-art-of-storytelling",
         "url":"/classes/neil-gaiman-teaches-the-art-of-storytelling",
         "category":"Writing",
         "trailer_slug":null,
         "description":"Award-winning author Neil Gaiman has spent more than a quarter of a century crafting vivid, absorbing fiction. Now, the author of Stardust, Coraline, and The Sandman teaches his approach to imaginative storytelling. Learn how to find your unique voice, develop original ideas, and breathe life into your characters. Discover Neil’s philosophy on what drives a story—and open new windows to the stories inside you.",
         "status":"available",
         "instructor_name":"Neil Gaiman",
         "objectID":"97"
      },
      {
         "id":96,
         "class_name":"Howard Schultz Leading A Values Based Business",
         "instructor":"Howard Schultz",
         "headline":"Business Leadership",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2375/original/1547754295-Headshot.jpg?1547754295",
         "class slug":"howard-schultz-leading-a-values-based-business",
         "url":"/classes/howard-schultz-leading-a-values-based-business",
         "category":"Business, Politics & Society",
         "trailer_slug":null,
         "description":"Former Starbucks CEO Howard Schultz rose from a childhood in public housing to leading a company that revolutionized the way the world drinks coffee. With no formal business education, he relied on his values while growing a 13-store chain into a global brand with more than 250,000 employees. In his 90-minute video series, Howard shares what he’s learned about values-based leadership and being an entrepreneur. ",
         "status":"available",
         "instructor_name":"Howard Schultz",
         "objectID":"96"
      },
      {
         "id":95,
         "class_name":"Jodie Foster Teaches Filmmaking",
         "instructor":"Jodie Foster",
         "headline":"Teaches Filmmaking",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2344/original/1547510090-Headshot.jpg?1547510090",
         "class slug":"jodie-foster-teaches-filmmaking",
         "url":"/classes/jodie-foster-teaches-filmmaking",
         "category":"Film & TV",
         "trailer_slug":null,
         "description":"Go behind the scenes with two-time Oscar-winner Jodie Foster, star of Silence of the Lambs and director of Little Man Tate. In her first online class, she’ll teach you how to bring your vision to life. Jodie brings her experience on both sides of the camera to guide you through every step of the filmmaking process, from storyboarding to casting and camera coverage. Everyone has a story. Learn how to tell yours.",
         "status":"available",
         "instructor_name":"Jodie Foster",
         "objectID":"95"
      },
      {
         "id":94,
         "class_name":"Will Wright Teaches Game Design And Theory",
         "instructor":"Will Wright",
         "headline":"Teaches Game Design and Theory",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2319/original/1545252289-Headshot.jpg?1545252289",
         "class slug":"will-wright-teaches-game-design-and-theory",
         "url":"/classes/will-wright-teaches-game-design-and-theory",
         "category":"Design, Photography, & Fashion",
         "trailer_slug":null,
         "description":"Learn the art and science of game design with Will Wright, the mind behind some of the most popular simulation games of all time—<span style=\"font-style:italic\">SimCity</span> and <span style=\"font-style:italic\">The Sims</span>. Will teaches you how to design games that empower players and unleash their creativity. You’ll develop a toolset for understanding player psychology, as well as learn Will's approach to generating and pitching ideas, prototyping, playtesting, and building a community.",
         "status":"available",
         "instructor_name":"Will Wright",
         "objectID":"94"
      },
      {
         "id":92,
         "class_name":"Carlos Santana Teaches The Art And Soul Of Guitar",
         "instructor":"Carlos Santana",
         "headline":"Teaches the Art and Soul of Guitar",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2272/original/1544749255-Headshot.jpg?1544749255",
         "class slug":"carlos-santana-teaches-the-art-and-soul-of-guitar",
         "url":"/classes/carlos-santana-teaches-the-art-and-soul-of-guitar",
         "category":"Music & Entertainment",
         "trailer_slug":null,
         "description":"With 10 Grammys and almost 50 years on stage, Carlos teaches you his spiritual take on playing guitar. Learn how he weaves emotion, artistic expression, and musical styles from across the world to create a sound that transcends genre and connects with audiences. Join Carlos in his studio as he breaks down his process note by note—so you can discover the soul of your sound.",
         "status":"available",
         "instructor_name":"Carlos Santana",
         "objectID":"92"
      },
      {
         "id":91,
         "class_name":"James Suckling Teaches Wine Appreciation",
         "instructor":"James Suckling",
         "headline":"Teaches Wine Appreciation",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2245/original/1544170587-Headshot.jpg?1544170587",
         "class slug":"james-suckling-teaches-wine-appreciation",
         "url":"/classes/james-suckling-teaches-wine-appreciation",
         "category":"Culinary Arts",
         "trailer_slug":null,
         "description":"Called one of the “world’s most powerful wine critics,” James Suckling has tasted more than 200,000 wines over the past 40 years. In his MasterClass, James tours legendary Tuscan vineyards and teaches you to explore the stories, history, and people behind every bottle. Deepen your knowledge of the properties in each sip, cultivate your passion, and choose, order, and pair wines with confidence.",
         "status":"available",
         "instructor_name":"James Suckling",
         "objectID":"91"
      },
      {
         "id":90,
         "class_name":"Jimmy Chin Teaches Adventure Photography",
         "instructor":"Jimmy Chin",
         "headline":"Teaches Adventure Photography",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2215/original/1543616552-Headshot.jpg?1543616552",
         "class slug":"jimmy-chin-teaches-adventure-photography",
         "url":"/classes/jimmy-chin-teaches-adventure-photography",
         "category":"Design, Photography, & Fashion",
         "trailer_slug":null,
         "description":"Jimmy Chin has built his career taking photos at the top of the world, earning him the cover of National Geographic and multiple awards. Now he’s taking you on location to teach you techniques for capturing breathtaking shots under high-stakes conditions. Learn his different creative approaches for commercial shoots, editorial spreads, and passion projects. Gather the gear—and the perspective—to bring your photography to new heights.",
         "status":"available",
         "instructor_name":"Jimmy Chin",
         "objectID":"90"
      },
      {
         "id":9,
         "class_name":"Werner Herzog Teaches Filmmaking",
         "instructor":"Werner Herzog",
         "headline":"Teaches Filmmaking",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/249/original/1463524207-WH-headshot-PE-1.jpg?1463524207",
         "class slug":"werner-herzog-teaches-filmmaking",
         "url":"/classes/werner-herzog-teaches-filmmaking",
         "category":"Film & TV",
         "trailer_slug":"3foqvgp85m",
         "description":"When the legendary director Werner Herzog was 19, he stole a camera and made his first movie. 70 films and 50 awards later, Werner is teaching documentary and feature filmmaking. You’ll learn storytelling, cinematography, locations, self-financing, documentary interview techniques, and how to bring your ideas to life. By the end, you’ll make uncompromising films.",
         "status":"available",
         "objectID":"9"
      },
      {
         "id":86,
         "class_name":"Mira Nair Teaches Independent Filmmaking",
         "instructor":"Mira Nair",
         "headline":"Teaches Independent Filmmaking",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2115/original/1542829582-Headshot.jpg?1542829582",
         "class slug":"mira-nair-teaches-independent-filmmaking",
         "url":"/classes/mira-nair-teaches-independent-filmmaking",
         "category":"Film & TV",
         "trailer_slug":"",
         "description":"Oscar-nominated filmmaker Mira Nair approaches directing with the “heart of a poet and the skin of an elephant”—spurred on by rejection and fighting to bring uncompromising stories to film. In the Golden Lion-winning director’s MasterClass, learn to make a big impact on a small budget, evoke the best from actors and non-actors, and protect your creative vision so you tell the story that can only come from you.",
         "status":"available",
         "instructor_name":"Mira Nair",
         "objectID":"86"
      },
      {
         "id":85,
         "class_name":"Dominique Ansel Teaches French Pastry Fundamentals",
         "instructor":"Dominique Ansel",
         "headline":"Teaches French Pastry Fundamentals",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2086/original/1542331031-Headshot.jpg?1542331031",
         "class slug":"dominique-ansel-teaches-french-pastry-fundamentals",
         "url":"/classes/dominique-ansel-teaches-french-pastry-fundamentals",
         "category":"Culinary Arts",
         "trailer_slug":"",
         "description":"Celebrated for his innovative twists on classic desserts, Cronut® creator and James Beard Award-winner Dominique Ansel has been called the “World’s Best Pastry Chef.” In his MasterClass, Dominique teaches his essential techniques for perfect pastries. Learn his precise methods, add classic recipes to your repertoire, and explore texture and flavor inspirations to delight friends and family with your own decadent desserts.",
         "status":"available",
         "instructor_name":"Dominique Ansel",
         "objectID":"85"
      },
      {
         "id":84,
         "class_name":"Thomas Keller Teaches Cooking Techniques Meats Stocks And Sauces",
         "instructor":"Thomas Keller",
         "headline":"Teaches Cooking Techniques II: Meats, Stocks, and Sauces",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2051/original/1541703026-Headshot.jpg?1541703026",
         "class slug":"thomas-keller-teaches-cooking-techniques-meats-stocks-and-sauces",
         "url":"/classes/thomas-keller-teaches-cooking-techniques-meats-stocks-and-sauces",
         "category":"Culinary Arts",
         "trailer_slug":"",
         "description":"As a follow-up to his first MasterClass, Chef Keller devotes his second class to beef, duck, chicken, pork, and veal—and the techniques he uses to prepare them. Learn to sauté, pan and oven roast, braise, fry, and grill, and to select the best cut of meat for each technique with confidence. Then, learn to make the stocks and sauces that are essentials in Chef Keller’s restaurant kitchens. ",
         "status":"available",
         "instructor_name":"Thomas Keller",
         "objectID":"84"
      },
      {
         "id":82,
         "class_name":"Dan Brown Teaches Writing Thrillers",
         "instructor":"Dan Brown",
         "headline":"Teaches Writing Thrillers",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2019/original/1541110615-Headshot.jpg?1541110615",
         "class slug":"dan-brown-teaches-writing-thrillers",
         "url":"/classes/dan-brown-teaches-writing-thrillers",
         "category":"Writing",
         "trailer_slug":"",
         "description":"Packed with secret symbols and high-stakes suspense, Dan Brown’s thrillers have sold more than 250 million copies, including one of the world’s best-selling novels, <span style=\"font-style:italic\">The Da Vinci Code.</span>  In his MasterClass, Dan unveils his step-by-step process for turning ideas into gripping narratives. Learn his methods for researching like a pro, crafting characters, and sustaining suspense all the way to a dramatic surprise ending.",
         "status":"available",
         "instructor_name":"Dan Brown",
         "objectID":"82"
      },
      {
         "id":81,
         "class_name":"Paul Krugman Teaches Economics And Society",
         "instructor":"Paul Krugman",
         "headline":"Teaches Economics and Society",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1992/original/1540519373-Headshot.jpg?1540519373",
         "class slug":"paul-krugman-teaches-economics-and-society",
         "url":"/classes/paul-krugman-teaches-economics-and-society",
         "category":"Politics & Society",
         "trailer_slug":"",
         "description":"For Nobel Prize-winning economist Paul Krugman, economics is not a set of answers, it’s a way of understanding the world. In his MasterClass, Paul teaches you the economic principles that shape political and social issues—like access to health care, the tax debate, globalization, and political polarization. Heighten your ability to read between the lines and decipher the underlying economics at play.",
         "status":"available",
         "instructor_name":"Paul Krugman",
         "objectID":"81"
      },
      {
         "id":80,
         "class_name":"David Axelrod And Karl Rove Teach Campaign Strategy And Messaging",
         "instructor":"David Axelrod and Karl Rove",
         "headline":"Teach Campaign Strategy and Messaging",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1892/original/1540359804-Headshot.jpg?1540359804",
         "class slug":"david-axelrod-and-karl-rove-teach-campaign-strategy-and-messaging",
         "url":"/classes/david-axelrod-and-karl-rove-teach-campaign-strategy-and-messaging",
         "category":"Politics & Society",
         "trailer_slug":"",
         "description":"David Axelrod and Karl Rove reach across the aisle to offer an inside look at winning campaign strategies. The respective architects of Barack Obama’s and George W. Bush’s historic election victories teach how to develop a campaign platform and reach an audience with consistent messaging. Find the inspiration and tools to get involved at any level, or simply become a more informed, engaged citizen.",
         "status":"available",
         "instructor_name":"David Axelrod and Karl Rove",
         "objectID":"80"
      },
      {
         "id":79,
         "class_name":"Tom Morello Teaches Electric Guitar",
         "instructor":"Tom Morello",
         "headline":"Teaches Electric Guitar",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1861/original/1540187470-Headshot.jpg?1540187470",
         "class slug":"tom-morello-teaches-electric-guitar",
         "url":"/classes/tom-morello-teaches-electric-guitar",
         "category":"Music & Entertainment",
         "trailer_slug":"",
         "description":"Tom Morello is a two-time Grammy winner, and one of Rolling Stone’s “Greatest Guitarists of All Time.” In his first online class, the co-founder of Rage Against the Machine will teach you the riffs, rhythms, and solos that launched his career and sent his music to the top of the charts. Tom will share his approach to making music that challenges the status quo, and teach you how to create your own musical style.",
         "status":"unavailable",
         "objectID":"79"
      },
      {
         "id":78,
         "class_name":"Gordon Ramsay Teaches Cooking Restaurant Recipes At Home",
         "instructor":"Gordon Ramsay",
         "headline":"Teaches Cooking II: Restaurant Recipes at Home",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1821/original/1536703255-Headshot.jpg?1536703255",
         "class slug":"gordon-ramsay-teaches-cooking-restaurant-recipes-at-home",
         "url":"/classes/gordon-ramsay-teaches-cooking-restaurant-recipes-at-home",
         "category":"Culinary Arts",
         "trailer_slug":"",
         "description":"It’s more than dinner, it’s a dining experience. Gordon Ramsay returns with a second MasterClass to teach you how to prep, plate, and pair recipes that wow guests. With 13 restaurant-inspired dishes—designed to cook at home—you’ll learn how to build elevated courses from appetizer to dessert using everyday ingredients.",
         "status":"available",
         "objectID":"78"
      },
      {
         "id":77,
         "class_name":"Ken Burns Teaches Documentary Filmmaking",
         "instructor":"Ken Burns",
         "headline":"Teaches Documentary Filmmaking",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1792/original/1533594409-Headshot.jpg?1533594409",
         "class slug":"ken-burns-teaches-documentary-filmmaking",
         "url":"/classes/ken-burns-teaches-documentary-filmmaking",
         "category":"Film & TV",
         "trailer_slug":"co2yrtnqa1",
         "description":"Since its 2017 debut, Ken Burns’s <span style=\"font-style:italic\">The Vietnam War</span> has enthralled over 39 million viewers by painting an intimate and revealing portrait of history. Learn how Ken captivates audiences with his ability to distill vast research and complex truths into compelling narratives. From first treatment to final edit, Ken teaches his documentary filmmaking techniques that “wake the dead” to bring their stories to life.",
         "status":"pre_enroll",
         "objectID":"77"
      },
      {
         "id":76,
         "class_name":"Margaret Atwood Teaches Creative Writing",
         "instructor":"Margaret Atwood",
         "headline":"Teaches Creative Writing",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1743/original/1530892634-Headshot.jpg?1530892634",
         "class slug":"margaret-atwood-teaches-creative-writing",
         "url":"/classes/margaret-atwood-teaches-creative-writing",
         "category":"Writing",
         "trailer_slug":"wjbphnxdne",
         "description":"Called the “Prophet of Dystopia,” Margaret Atwood is one of the most influential literary voices of our generation. In her first-ever online class, the author of <span style=\"font-style:italic\">The Handmaid’s Tale</span>  teaches how she crafts compelling stories—from historical to speculative fiction—that remain timeless and relevant. Explore Margaret’s creative process for developing ideas into novels with strong structures and nuanced characters.",
         "status":"available",
         "objectID":"76"
      },
      {
         "id":75,
         "class_name":"Natalie Portman Teaches Acting",
         "instructor":"Natalie Portman",
         "headline":"Teaches Acting",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2470/original/1551745582-Headshot.jpg?1551745582",
         "class slug":"natalie-portman-teaches-acting",
         "url":"/classes/natalie-portman-teaches-acting",
         "category":"Film & TV",
         "trailer_slug":"",
         "description":"Natalie Portman began acting professionally at 12 and won an Oscar before she turned 30. As a self-taught actor, she uses personal techniques to create compelling, complex characters. In her first-ever acting class, Natalie shows how empathy is at the core of every great performance, how to bring real-life details into every role, and how to build your own creative process. Get ready for your breakout performance.",
         "status":"available",
         "instructor_name":"Natalie Portman",
         "objectID":"75"
      },
      {
         "id":74,
         "class_name":"Daniel Negreanu Teaches Poker",
         "instructor":"Daniel Negreanu",
         "headline":"Teaches Poker",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1677/original/1528446156-Headshot.jpg?1528446156",
         "class slug":"daniel-negreanu-teaches-poker",
         "url":"/classes/daniel-negreanu-teaches-poker",
         "category":"Sports & Games",
         "trailer_slug":"x3yr6p8htw",
         "description":"Put yourself across the felt from Daniel Negreanu—the biggest live tournament poker winner of all time. The six-time World Series of Poker champion teaches advanced theory and practice through hand-reviews of his winning games. Learn how to sharpen your mental game through demos on reading opponents and spotting tells. Join Daniel at the table to learn how to increase your win rate, grow your ROI, and get your game “In the Money.”",
         "status":"available",
         "objectID":"74"
      },
      {
         "id":73,
         "class_name":"Rl Stine Teaches Writing For Young Audiences",
         "instructor":"R.L. Stine",
         "headline":"Teaches Writing for Young Audiences",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1564/original/1522098109-Headshot.jpg?1522098109",
         "class slug":"rl-stine-teaches-writing-for-young-audiences",
         "url":"/classes/rl-stine-teaches-writing-for-young-audiences",
         "category":"Writing",
         "trailer_slug":"qlcxr56zzj",
         "description":"Award-winning novelist R.L. Stine wrote jokes and funny stories for 20 years before he switched gears and became a horror-writing legend. Since then, the author of the <span style=\"font-style:italic\">Goosebumps</span> and <span style=\"font-style:italic\">Fear Street</span> series has sold more than 400 million copies. In his first-ever online class, Bob takes the fear out of fiction writing. Whether you’re a beginner or a pro, you’ll learn new ways to conquer writer's block, develop plots, and build nail-biting suspense that will thrill young readers.",
         "status":"available",
         "objectID":"73"
      },
      {
         "id":72,
         "class_name":"Spike Lee Teaches Filmmaking",
         "instructor":"Spike Lee",
         "headline":"Teaches Filmmaking",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1534/original/1521243500-Headshot.jpg?1521243500",
         "class slug":"spike-lee-teaches-filmmaking",
         "url":"/classes/spike-lee-teaches-filmmaking",
         "category":"Film & TV",
         "trailer_slug":"tmzchcupcz",
         "description":"Spike Lee didn’t just direct his award-winning 1986 feature debut, <span style=\"font-style:italic\">She’s Gotta Have It</span>. He was also the writer, star, truck driver, location scout, electrician, and caterer—because that’s what it took to get his film made. In his first-ever online class, the visionary behind <span style=\"font-style:italic\"> Do the Right Thing</span>, <span style=\"font-style:italic\">Malcolm X</span>, and <span style=\"font-style:italic\">25th Hour</span> lets you in on his uncompromising approach to filmmaking. Learn about writing, self-producing, working with actors, and making movies that break down barriers.\r\n",
         "status":"pre_enroll",
         "objectID":"72"
      },
      {
         "id":71,
         "class_name":"Chris Hadfield Teaches Space Exploration",
         "instructor":"Chris Hadfield",
         "headline":"Teaches Space Exploration",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1603/original/1523379082-Headshot.jpg?1523379082",
         "class slug":"chris-hadfield-teaches-space-exploration",
         "url":"/classes/chris-hadfield-teaches-space-exploration",
         "category":"Science & Technology",
         "trailer_slug":"phz14v2vtu",
         "description":"Impossible things happen. At age nine, Chris Hadfield knew he wanted to go to space. He eventually went there three times, becoming a commander of the International Space Station. In his MasterClass, Chris teaches you what it takes to explore space and what the future holds for humans in the final frontier. Learn about the science of space travel, life as an astronaut, and how flying in space will forever change the way you think about living on Earth.",
         "status":"available",
         "objectID":"71"
      },
      {
         "id":70,
         "class_name":"Judd Apatow Teaches Comedy",
         "instructor":"Judd Apatow",
         "headline":"Teaches Comedy",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1457/original/1518814821-Headshot.jpg?1518814821",
         "class slug":"judd-apatow-teaches-comedy",
         "url":"/classes/judd-apatow-teaches-comedy",
         "category":"Film & TV",
         "trailer_slug":"dhs1oz0xzx",
         "description":"No joke: At age 15, Judd Apatow took a dishwashing job at a comedy club to watch the acts. Today, he’s the comedic genius behind hits including <span style=\"font-style:italic\">The 40-Year-Old Virgin</span>, <span style=\"font-style:italic\">Knocked Up</span>, <span style=\"font-style:italic\">Bridesmaids</span>, and <span style=\"font-style:italic\">Freaks and Geeks</span>. In his first-ever online class, the Emmy Award winner teaches you how to create hilarious storylines, write great stand-up, and direct comedies that leave audiences laughing. ",
         "status":"available",
         "objectID":"70"
      },
      {
         "id":7,
         "class_name":"Christina Aguilera Teaches Singing",
         "instructor":"Christina Aguilera",
         "headline":"Teaches Singing",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/238/original/1460066723-PR-CA-headshot-PO.jpg?1460066723",
         "class slug":"christina-aguilera-teaches-singing",
         "url":"/classes/christina-aguilera-teaches-singing",
         "category":"Music & Entertainment",
         "trailer_slug":"16orhpcj5q",
         "description":"Christina teaches you how to expand your range, find your voice, and master the techniques that have earned her six Grammy Awards. You'll learn warm-up exercises, breath control, vibrato, her signature growls, and hear Christina break down her biggest hits. There has never been a singing class like this before. ",
         "status":"available",
         "objectID":"7"
      },
      {
         "id":69,
         "class_name":"Malcolm Gladwell Teaches Writing",
         "instructor":"Malcolm Gladwell",
         "headline":"Teaches Writing",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1428/original/1518557721-Headshot.jpg?1518557721",
         "class slug":"malcolm-gladwell-teaches-writing",
         "url":"/classes/malcolm-gladwell-teaches-writing",
         "category":"Writing",
         "trailer_slug":"ko6vqef7fw",
         "description":"Ketchup. Crime. Quarterbacks. Thanks to Malcolm Gladwell, these ordinary subjects have helped millions of readers devour complex ideas like behavioral economics and performance prediction. Now, the renowned storyteller and best-selling author of <span style=\"font-style:italic\">Blink</span> and <span style=\"font-style:italic\">The Tipping Point</span> is teaching his craft online for the first time. Write stories that captivate by learning how Malcolm researches topics, crafts characters, and distills big ideas into simple, powerful narratives.",
         "status":"available",
         "objectID":"69"
      },
      {
         "id":67,
         "class_name":"Armin Van Buuren Teaches Dance Music",
         "instructor":"Armin van Buuren",
         "headline":"Teaches Dance Music",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1192/original/1512075692-Headshot.jpg?1512075692",
         "class slug":"armin-van-buuren-teaches-dance-music",
         "url":"/classes/armin-van-buuren-teaches-dance-music",
         "category":"Music & Entertainment",
         "trailer_slug":"8kr31gnt8c",
         "description":"Every week, Armin van Buuren puts 41 million listeners into A State of Trance on his radio show. In his first-ever online class, the platinum-selling DJ breaks down his hits—and builds a track from scratch—to show you how he produces, performs, and promotes dance music. You’ll learn his technical process for using samples and plug-ins, mixing, recording vocals, and building a DJ set. Your crowd is waiting.",
         "status":"available",
         "objectID":"67"
      },
      {
         "id":66,
         "class_name":"Thomas Keller Teaches Cooking Techniques",
         "instructor":"Thomas Keller",
         "headline":"Teaches Cooking Techniques",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1086/original/1510618603-Headshot.jpg?1510618603",
         "class slug":"thomas-keller-teaches-cooking-techniques",
         "url":"/classes/thomas-keller-teaches-cooking-techniques",
         "category":"Culinary Arts",
         "trailer_slug":"3b3ufwngjr",
         "description":"Thomas Keller is the only American-born chef to hold multiple Michelin three-star ratings. In his first online class, the chef behind The French Laundry teaches you how to master the fundamentals of cooking. Learn about handling kitchen tools, preparing foundational ingredients (like vegetables, eggs, and pasta), and the science behind cooking. Gain the skills—and confidence—that will help you execute recipes to perfection.",
         "status":"available",
         "objectID":"66"
      },
      {
         "id":65,
         "class_name":"Alice Waters Teaches The Art Of Home Cooking",
         "instructor":"Alice Waters",
         "headline":"Teaches the Art of Home Cooking",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1060/original/1510617641-Headshot.jpg?1510617641",
         "class slug":"alice-waters-teaches-the-art-of-home-cooking",
         "url":"/classes/alice-waters-teaches-the-art-of-home-cooking",
         "category":"Culinary Arts",
         "trailer_slug":"z7rna8w3bq",
         "description":"Alice Waters started America’s farm-to-table revolution. When she founded the iconic restaurant Chez Panisse, her local, organic ingredients sparked a movement—and earned her the James Beard Award for Outstanding Chef. In her first-ever online class, Alice opens the doors of her home kitchen to teach you how to pick seasonal ingredients, cook healthy and beautiful meals, and change your life by changing the food you make at home.",
         "status":"available",
         "objectID":"65"
      },
      {
         "id":64,
         "class_name":"Wolfgang Puck Teaches Cooking",
         "instructor":"Wolfgang Puck",
         "headline":"Teaches Cooking",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1026/original/1510352588-Headshot.jpg?1510352588",
         "class slug":"wolfgang-puck-teaches-cooking",
         "url":"/classes/wolfgang-puck-teaches-cooking",
         "category":"Culinary Arts",
         "trailer_slug":"1nnu4rsa37",
         "description":"Legend has it Wolfgang Puck came up with his famous smoked salmon pizza when his restaurant ran out of bagels—and ended up changing the way America cooks. In his MasterClass, the five-time James Beard Award-winning chef behind more than 100 restaurants brings you into his kitchen. You’ll learn not only how to master starters, mains, sides, and cocktails, but also how to take risks to create memorable recipes of your own.",
         "status":"available",
         "objectID":"64"
      },
      {
         "id":63,
         "class_name":"Stephen Curry Teaches Shooting Ball Handling And Scoring",
         "instructor":"Stephen Curry",
         "headline":"Teaches Shooting, Ball-Handling, and Scoring",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1002/original/1510789757-Headshot_V2.jpg?1510789757",
         "class slug":"stephen-curry-teaches-shooting-ball-handling-and-scoring",
         "url":"/classes/stephen-curry-teaches-shooting-ball-handling-and-scoring",
         "category":"Sports & Games",
         "trailer_slug":"ypgpks3zfs",
         "description":"Stephen was barely recruited by college coaches. Today, he’s a three-time champion and one of the best shooters in NBA history. Join Stephen on the court in his first-ever online class as he teaches you how to improve your shooting mechanics, and leads you through ball-handling, footwork, and scoring drills. Then see the game through Stephen’s eyes as he analyzes NBA game footage to help you elevate your basketball IQ.",
         "status":"available",
         "objectID":"63"
      },
      {
         "id":62,
         "class_name":"Helen Mirren Teaches Acting",
         "instructor":"Helen Mirren",
         "headline":"Teaches Acting",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/953/original/1510256346-Headshot.jpg?1510256346",
         "class slug":"helen-mirren-teaches-acting",
         "url":"/classes/helen-mirren-teaches-acting",
         "category":"Film & TV",
         "trailer_slug":"rrwzb6v4ze",
         "description":"Oscar, Golden Globe, Emmy, and Tony winner Helen Mirren is one of the greatest actresses of our time. In her first online class, she discusses the dualism that is core to her method: the necessity for mastering technique (craft) and then letting go so that your imagination can take over (art). Learn how to break down a script, research characters, and master techniques so you can transcend them to find freedom in every role.",
         "status":"available",
         "objectID":"62"
      },
      {
         "id":61,
         "class_name":"Ron Howard Teaches Directing",
         "instructor":"Ron Howard",
         "headline":"Teaches Directing",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/918/original/1509412998-Headshot.jpg?1509412998",
         "class slug":"ron-howard-teaches-directing",
         "url":"/classes/ron-howard-teaches-directing",
         "category":"Film & TV",
         "trailer_slug":"k5g5v3w6fm",
         "description":"Ron Howard made his first film in 22 days with $602,000. Today, his movies have grossed over $1.8 billion. In his first-ever online class, the Oscar-winning director of <span style=\"font-style:italic\">Apollo 13</span> and <span style=\"font-style:italic\">A Beautiful Mind</span> decodes the craft of directing like never before. In lessons and on-set workshops, you’ll learn how to evaluate ideas, work with actors, block scenes, and bring your vision to the screen—whether it’s a laptop or an IMAX theater.",
         "status":"available",
         "objectID":"61"
      },
      {
         "id":60,
         "class_name":"Marc Jacobs Teaches Fashion Design",
         "instructor":"Marc Jacobs",
         "headline":"Teaches Fashion Design",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/978/original/1510266698-Headshot.jpg?1510266698",
         "class slug":"marc-jacobs-teaches-fashion-design",
         "url":"/classes/marc-jacobs-teaches-fashion-design",
         "category":"Design, Photography, & Fashion",
         "trailer_slug":"ehxxtsggvh",
         "description":"Marc Jacobs’ infamous grunge collection got him fired. It also won him the CFDA Womenswear Designer of the Year Award. In his first online class, the 11-time CFDA Award-winning designer teaches his hands-on process for creating clothes that push boundaries and set trends. Learn Marc’s construction techniques, how he creates unique shapes and silhouettes, and how you can develop your own ideas from the first sketch to the final piece.",
         "status":"available",
         "objectID":"60"
      },
      {
         "id":6,
         "class_name":"Serena Williams Teaches Tennis",
         "instructor":"Serena Williams",
         "headline":"Teaches Tennis",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1476/original/1520559058-sw.jpg?1520559058",
         "class slug":"serena-williams-teaches-tennis",
         "url":"/classes/serena-williams-teaches-tennis",
         "category":"Sports & Games",
         "trailer_slug":"vo1abo4n7k",
         "description":"Serena Williams, the world’s #1 ranked women's tennis player and winner of 23 Grand Slam singles titles, teaches you tennis and reveals the secrets of her game. This is as close as you can get to a private lesson with one of the world’s greatest tennis players.",
         "status":"available",
         "objectID":"6"
      },
      {
         "id":59,
         "class_name":"Bob Woodward Teaches Investigative Journalism",
         "instructor":"Bob Woodward",
         "headline":"Teaches Investigative Journalism",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/892/original/1508526232-Headshot.jpg?1508526232",
         "class slug":"bob-woodward-teaches-investigative-journalism",
         "url":"/classes/bob-woodward-teaches-investigative-journalism",
         "category":"Politics & Society",
         "trailer_slug":"4m095lpcyq",
         "description":"Bob Woodward was just 29 when he changed a nation. His Watergate reporting with Carl Bernstein helped expose the corruption of the Nixon presidency. Two Pulitzer Prizes and eighteen best-selling books later, the legendary journalist is teaching his first-ever online class for anyone who wants to find the truth. Learn to investigate a story, interview sources, and understand how the news is written. The next history-making story might be yours.",
         "status":"available",
         "objectID":"59"
      },
      {
         "id":58,
         "class_name":"Samuel L Jackson Teaches Acting",
         "instructor":"Samuel L. Jackson",
         "headline":"Teaches Acting",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/871/original/1508193983-SLJ_Headshot_V1_A.jpg?1508193983",
         "class slug":"samuel-l-jackson-teaches-acting",
         "url":"/classes/samuel-l-jackson-teaches-acting",
         "category":"Film & TV",
         "trailer_slug":"0hppggncva",
         "description":"As a kid, Samuel L. Jackson stuttered so badly that he stopped talking for almost a year. Today he’s one of the world’s most successful actors, with roles in over 100 films, including <span style=\"font-style:italic\">Pulp Fiction</span> and <span style=\"font-style:italic\">The Avengers</span>. For the first time, the Oscar nominated star teaches how he creates memorable characters, powerful performances, and a long-lasting career. Learn to master auditions, analyze scripts, and find the truth in every role you play.",
         "status":"available",
         "objectID":"58"
      },
      {
         "id":57,
         "class_name":"Judy Blume Teaches Writing",
         "instructor":"Judy Blume",
         "headline":"Teaches Writing",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/819/original/1506388998-JBL_Headshot_Final.jpg?1506388998",
         "class slug":"judy-blume-teaches-writing",
         "url":"/classes/judy-blume-teaches-writing",
         "category":"Writing",
         "trailer_slug":"cltt891uwz",
         "description":"Judy Blume broke the rules. Her refreshingly honest children’s books were banned by hundreds of libraries—and loved by generations of readers, who bought 85 million copies of classics like <span style=\"font-style:italic\">Are You There God? It’s Me, Margaret</span> and <span style=\"font-style:italic\">Superfudge</span>. In her first online class, the award-winning author teaches you how to invent vivid characters, write realistic dialogue, and turn your experiences into stories people will treasure.\r\n",
         "status":"available",
         "objectID":"57"
      },
      {
         "id":56,
         "class_name":"Martin Scorsese Teaches Filmmaking",
         "instructor":"Martin Scorsese",
         "headline":"Teaches Filmmaking",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/786/original/1505853847-headshot.jpg?1505853847",
         "class slug":"martin-scorsese-teaches-filmmaking",
         "url":"/classes/martin-scorsese-teaches-filmmaking",
         "category":"Film & TV",
         "trailer_slug":"9lqumh5t7u",
         "description":"Martin Scorsese drew his first storyboard when he was eight. Today he’s a legendary director whose films—from <span style=\"font-style:italic\">Mean Streets</span> to  <span style=\"font-style:italic\">The Wolf of Wall Street</span>—have shaped movie history. In his first-ever online class, the Oscar winner teaches his approach to filmmaking, from storytelling to editing to working with actors. He deconstructs films and breaks down his craft, changing how you make—and watch—movies.",
         "status":"available",
         "objectID":"56"
      },
      {
         "id":55,
         "class_name":"Herbie Hancock Teaches Jazz",
         "instructor":"Herbie Hancock",
         "headline":"Teaches Jazz",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/696/original/1497396636-HH_Headshot_V1_A.jpg?1497396636",
         "class slug":"herbie-hancock-teaches-jazz",
         "url":"/classes/herbie-hancock-teaches-jazz",
         "category":"Music & Entertainment",
         "trailer_slug":"i04uh5a1no",
         "description":"Herbie Hancock’s jazz career started in his family’s living room, listening to his favorite records and trying to play along. Now, he’s one of the most celebrated musicians in the world. Join Herbie at the piano as he shares his approach to improvisation, composition, and harmony. Gain access to 10+ original piano transcriptions, including 5 exclusive solo performances.\r\n",
         "status":"available",
         "objectID":"55"
      },
      {
         "id":54,
         "class_name":"Garry Kasparov Teaches Chess",
         "instructor":"Garry Kasparov",
         "headline":"Teaches Chess",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/667/original/1496916192-GK_Headshot_V2_A.jpg?1496916192",
         "class slug":"garry-kasparov-teaches-chess",
         "url":"/classes/garry-kasparov-teaches-chess",
         "category":"Sports & Games",
         "trailer_slug":"1c8q2l4nvy",
         "description":"At age 22, Garry Kasparov became the youngest world chess champion. After beating Bobby Fischer’s peak rating, he outranked his fiercest competitors for over twenty years. Now, Garry is ready to share what made him a six-time World Chess Champion. Through detailed lessons, including his favorite openings and advanced tactics, you will develop the instincts and philosophy to become a stronger player. ",
         "status":"available",
         "objectID":"54"
      },
      {
         "id":53,
         "class_name":"Jane Goodall Teaches Conservation",
         "instructor":"Dr. Jane Goodall",
         "headline":"Teaches Conservation",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/644/original/1496380601-JG-profile-sm.jpg?1496380601",
         "class slug":"jane-goodall-teaches-conservation",
         "url":"/classes/jane-goodall-teaches-conservation",
         "category":"Politics & Society",
         "trailer_slug":"snozh5xwpq",
         "description":"“There is still a window of time. Nature can win if we give her a chance.” In her first ever online class, Dr. Jane Goodall teaches how you can conserve the environment. She also shares her research on the behavioral patterns of chimpanzees and what they taught her about conservation. You’ll learn how to “act locally” and protect the planet. ",
         "status":"available",
         "objectID":"53"
      },
      {
         "id":52,
         "class_name":"Diane Von Furstenberg Teaches Building A Fashion Brand",
         "instructor":"Diane von Furstenberg",
         "headline":"Teaches Building a Fashion Brand",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/624/original/1493844606-DVF_Headshot_V1_A.jpg?1493844606",
         "class slug":"diane-von-furstenberg-teaches-building-a-fashion-brand",
         "url":"/classes/diane-von-furstenberg-teaches-building-a-fashion-brand",
         "category":"Design, Photography, & Fashion",
         "trailer_slug":"o1t2ugj8op",
         "description":"In her 20s, Diane convinced a textile factory owner in Italy to let her produce her first designs. With those samples, she flew to New York City to build one of the world’s most iconic and enduring fashion brands. In her first online class, Diane teaches you how to build a brand. You’ll learn how to create a visual identity, build loyalty, stay true to your vision, and launch your product.",
         "status":"available",
         "objectID":"52"
      },
      {
         "id":5,
         "class_name":"Annie Leibovitz Teaches Photography",
         "instructor":"Annie Leibovitz",
         "headline":"Teaches Photography",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1477/original/1520559090-al.jpg?1520559090",
         "class slug":"annie-leibovitz-teaches-photography",
         "url":"/classes/annie-leibovitz-teaches-photography",
         "category":"Design, Photography, & Fashion",
         "trailer_slug":"s6fi8yxy5i",
         "description":"Annie was the first woman to be named chief photographer at Rolling Stone and the last person to take a portrait of John Lennon. In her first online class, Annie shows us that what makes a picture stunning isn’t the gear or technology—it’s the story. Annie teaches you her philosophy on photography—how to develop concepts, work with subjects, shoot with natural light, and bring images to life in post-production.  See the world through her eyes.",
         "status":"available",
         "objectID":"5"
      },
      {
         "id":2,
         "class_name":"Usher Teaches The Art Of Performance",
         "instructor":"Usher",
         "headline":"The Art Of Performance",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1478/original/1520559128-ur.jpg?1520559128",
         "class slug":"usher-teaches-the-art-of-performance",
         "url":"/classes/usher-teaches-the-art-of-performance",
         "category":"Music & Entertainment",
         "trailer_slug":"68fnbqeq6u",
         "description":"Usher, winner of 8 Grammy Awards, reveals the technical skills, career lessons and breakthrough advice that he has used to captivate audiences for over 25 years. For the first time ever, learn how Usher approaches performance and wins over audiences from the studio to the stage. There has never been a class like this before.",
         "status":"available",
         "objectID":"2"
      },
      {
         "id":19,
         "class_name":"David Mamet Teaches Dramatic Writing",
         "instructor":"David Mamet",
         "headline":"Teaches Dramatic Writing",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/574/original/1492646506-DaMa_Headshot_V2_A.jpg?1492646506",
         "class slug":"david-mamet-teaches-dramatic-writing",
         "url":"/classes/david-mamet-teaches-dramatic-writing",
         "category":"Writing",
         "trailer_slug":"0rj7vu7g02",
         "description":"David Mamet sat in on a poker game full of thieves and left with the inspiration for <span style=\"font-style:italic\">American Buffalo</span>. Now, the Pulitzer Prize-winning writer of <span style=\"font-style:italic\">Glengarry Glen Ross</span> takes you through his process for turning life's strangest moments into dramatic art. He'll teach you the rules of drama, the nuances of dialogue, and the skills to develop your own voice and create your masterpiece.",
         "status":"available",
         "objectID":"19"
      },
      {
         "id":18,
         "class_name":"Steve Martin Teaches Comedy",
         "instructor":"Steve Martin",
         "headline":"Teaches Comedy",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/526/original/1488402131-1488323196-SM_Headshot_V1_A.jpg?1488402131",
         "class slug":"steve-martin-teaches-comedy",
         "url":"/classes/steve-martin-teaches-comedy",
         "category":"Music & Entertainment",
         "trailer_slug":"azxp1sszx4",
         "description":"One of Steve’s first gigs was at the drive-in movies. When the audience liked a joke, they honked. In this class, Steve shares insights from performing for cars and humans over a 50-year career spanning sold-out arenas and blockbuster films. Learn how to find your voice, gather material, develop an act, and take your comedy to the next level. ",
         "status":"available",
         "objectID":"18"
      },
      {
         "id":17,
         "class_name":"Frank Gehry Teaches Design And Architecture",
         "instructor":"Frank Gehry",
         "headline":"Teaches Design and Architecture",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/515/original/1487196617-1486509198-FG_Headshot_V1_A.jpg?1487196617",
         "class slug":"frank-gehry-teaches-design-and-architecture",
         "url":"/classes/frank-gehry-teaches-design-and-architecture",
         "category":"Design, Photography, & Fashion",
         "trailer_slug":"aszkctragt",
         "description":"At 19 years old, Frank Gehry was a truck driver taking sculpture classes at night school. His vision for what architecture could accomplish went on to reshape our cities’ skylines, and the imaginations of artists and designers around the world. Now this master builder invites you into his never-before-seen model archive for a look into his creative process.",
         "status":"available",
         "objectID":"17"
      },
      {
         "id":16,
         "class_name":"Shonda Rhimes Teaches Writing For Television",
         "instructor":"Shonda Rhimes",
         "headline":"Teaches Writing for Television",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/431/original/1481755528-SR_Headshot_V1_A.jpg?1481755528",
         "class slug":"shonda-rhimes-teaches-writing-for-television",
         "url":"/classes/shonda-rhimes-teaches-writing-for-television",
         "category":"Film & TV",
         "trailer_slug":"lcc7eock7z",
         "description":"When Shonda Rhimes pitched <span style=\"font-style:italic\">Grey’s Anatomy</span> she got so nervous she had to start over. Twice. Since then, she has created and produced TV’s biggest hits. In her class, Shonda teaches you how to create compelling characters, write a pilot, pitch your idea, and stand out in the writers’ room. You’ll also get original pilot scripts, pitch notes, and series bibles from her shows. Welcome to Shondaland.",
         "status":"available",
         "objectID":"16"
      },
      {
         "id":14,
         "class_name":"Gordon Ramsay Teaches Cooking",
         "instructor":"Gordon Ramsay",
         "headline":"Teaches Cooking",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/407/original/1479680636-GR_Headshot_V1_A.jpg?1479680636",
         "class slug":"gordon-ramsay-teaches-cooking",
         "url":"/classes/gordon-ramsay-teaches-cooking",
         "category":"Culinary Arts",
         "trailer_slug":"a0mlnzn6px",
         "description":"This is Gordon Ramsay like you’ve never experienced. The seven-star Michelin chef takes you into his home kitchen to learn everything from kitchen setup and buying the freshest ingredients to constructing unforgettable dishes. In this MasterClass, you’re not just learning recipes, you’re learning how to take your cooking to the next level.",
         "status":"available",
         "objectID":"14"
      },
      {
         "id":13,
         "class_name":"Hans Zimmer Teaches Film Scoring",
         "instructor":"Hans Zimmer",
         "headline":"Teaches Film Scoring",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/386/original/1479451493-HZ_Headshot_V1_A.jpg?1479451493",
         "class slug":"hans-zimmer-teaches-film-scoring",
         "url":"/classes/hans-zimmer-teaches-film-scoring",
         "category":"Music & Entertainment",
         "trailer_slug":"lkhq1eeg4t",
         "description":"Hans Zimmer didn’t see a film until he was 12 years old. Since then, he’s scored over 150 films, including <span style=\"font-style:italic\">Inception</span>, <span style=\"font-style:italic\">The Lion King</span>, and <span style=\"font-style:italic\">The Dark Knight</span>. In his MasterClass, the self-taught Academy Award winner teaches how he creates sounds from nothing, composes compelling character themes, and scores a movie before ever seeing it. By the end, you’ll have everything you need to tell your story.",
         "status":"available",
         "objectID":"13"
      },
      {
         "id":12,
         "class_name":"Deadmau5 Teaches Electronic Music Production",
         "instructor":"Deadmau5",
         "headline":"Teaches Electronic Music Production",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/369/original/1479178167-DM5_Headshot_V1_A.jpg?1479178167",
         "class slug":"deadmau5-teaches-electronic-music-production",
         "url":"/classes/deadmau5-teaches-electronic-music-production",
         "category":"Music & Entertainment",
         "trailer_slug":"6md1t8d3kz",
         "description":"Before he was deadmau5, all Joel wanted for Christmas was old toasters to take apart. Now, in his MasterClass, watch him take his music apart. Joel teaches you how he approaches melodies, mixing and mastering to make unique sounds you can’t find in a cookie cutter sample pack. You’ll get not only his lessons, you’ll learn how to create your own music without spending money on million dollar gear.\r\n",
         "status":"available",
         "objectID":"12"
      },
      {
         "id":11,
         "class_name":"Reba Mcentire Teaches Country Music",
         "instructor":"Reba McEntire",
         "headline":"Teaches Country Music",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/303/original/1476326407-headshotv10.jpg?1476326407",
         "class slug":"reba-mcentire-teaches-country-music",
         "url":"/classes/reba-mcentire-teaches-country-music",
         "category":"Music & Entertainment",
         "trailer_slug":"",
         "description":"You know her songs. Her Oklahoma charm. Now learn directly from Reba in her first-ever online class. Join her as she records a never-before-heard song, creates a new acoustic version of Fancy, breaks down her hits, and delivers emotional performances on the stage of the Grand Ole Opry. This is more than a music class. This is Reba's life, business, and country music MasterClass. ",
         "status":"available",
         "objectID":"11"
      },
      {
         "id":105,
         "class_name":"Massimo Bottura Teaches Modern Italian Cooking",
         "instructor":"Massimo Bottura",
         "headline":"Teaches Modern Italian Cooking",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2914/original/1560886016-headshot.jpg?1560886016",
         "class slug":"massimo-bottura-teaches-modern-italian-cooking",
         "url":"/classes/massimo-bottura-teaches-modern-italian-cooking",
         "category":"Culinary Arts",
         "trailer_slug":null,
         "description":"Massimo Bottura, chef of the three-Michelin-star Osteria Francescana, treats his world-renowned restaurant as a laboratory of ideas. In his MasterClass, he shares how he transforms classic, regional Italian recipes into exciting modern dishes. You’ll learn how to make rich, flavorful tagliatelle al ragù, pumpkin risotto, and a MasterClass-exclusive Emilia Burger recipe. Develop your palate and embark on a culinary adventure. ",
         "status":"available",
         "instructor_name":"Massimo Bottura",
         "objectID":"105"
      },
      {
         "id":104,
         "class_name":"Itzhak Perlman Teaches Violin",
         "instructor":"Itzhak Perlman",
         "headline":"Teaches Violin",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2877/original/1559674140-headshot.jpg?1559674140",
         "class slug":"itzhak-perlman-teaches-violin",
         "url":"/classes/itzhak-perlman-teaches-violin",
         "category":"Music & Entertainment",
         "trailer_slug":null,
         "description":"The world’s reigning virtuoso violin player, Itzhak Perlman performs for presidents, royals, and classical music lovers around the world. Now the beloved Juilliard instructor and 15-time Grammy Award winner brings his passion for teaching to a wide audience for the first time. Learn fundamental techniques, practice strategies, and how to add richness and depth to your sound. Give your most dynamic performance yet.",
         "status":"available",
         "instructor_name":"Itzhak Perlman",
         "objectID":"104"
      },
      {
         "id":103,
         "class_name":"Phil Ivey Teaches Poker Strategy",
         "instructor":"Phil Ivey",
         "headline":"Teaches Poker Strategy",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2854/original/1558479481-headshot.jpg?1558479481",
         "class slug":"phil-ivey-teaches-poker-strategy",
         "url":"/classes/phil-ivey-teaches-poker-strategy",
         "category":"Sports & Games",
         "trailer_slug":null,
         "description":"At age 38, Phil Ivey became the youngest player to win 10 World Series of Poker bracelets. Now the man known for his enigmatic table presence—and widely regarded as the world’s best all-around poker player—gives you unprecedented access to his mental game. Learn poker strategy, pick up new poker tips, and review hands with the player who’s won more than $26 million in live tournament earnings.",
         "status":"available",
         "instructor_name":"Phil Ivey",
         "objectID":"103"
      },
      {
         "id":102,
         "class_name":"Aaron Franklin Teaches Texas Style Bbq",
         "instructor":"Aaron Franklin",
         "headline":"Teaches Texas-Style BBQ",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2815/original/1557859378-headshot.jpg?1557859378",
         "class slug":"aaron-franklin-teaches-texas-style-bbq",
         "url":"/classes/aaron-franklin-teaches-texas-style-bbq",
         "category":"Culinary Arts",
         "trailer_slug":null,
         "description":"Once a backyard hobbyist, Aaron Franklin is now the James Beard Award-winning owner of Franklin Barbecue, where the line for his famous smoked brisket is hours long. Now the Central Texas barbecue specialist teaches you his meticulous low and slow process for mouth-watering ribs, pork butt, and brisket. With perfectly seasoned cuts and optimal temperatures, you'll learn to handle an offset smoker like a true pitmaster.",
         "status":"available",
         "instructor_name":"Aaron Franklin",
         "objectID":"102"
      },
      {
         "id":101,
         "class_name":"Penn And Teller Teach The Art Of Magic",
         "instructor":"Penn & Teller",
         "headline":"Teach the Art of Magic",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2774/original/1556235534-PT_headshot.jpg?1556235534",
         "class slug":"penn-and-teller-teach-the-art-of-magic",
         "url":"/classes/penn-and-teller-teach-the-art-of-magic",
         "category":"Music & Entertainment",
         "trailer_slug":null,
         "description":"With more than 40 years performing together, Penn & Teller have sold out shows around the world, earned a star on Hollywood’s Walk of Fame, and created the longest-running headline act in Las Vegas. Now the legendary magicians are taking you behind the curtain. Learn fundamental magic tricks and the psychological tools that create amazement, at home or on stage. Expand your perception of the possible.",
         "status":"available",
         "instructor_name":"Penn & Teller",
         "objectID":"101"
      },
      {
         "id":100,
         "class_name":"Billy Collins Teaches Reading And Writing Poetry",
         "instructor":"Billy Collins",
         "headline":"Teaches Reading and Writing Poetry",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/2634/original/1555103361-headshot.jpg?1555103361",
         "class slug":"billy-collins-teaches-reading-and-writing-poetry",
         "url":"/classes/billy-collins-teaches-reading-and-writing-poetry",
         "category":"Writing",
         "trailer_slug":null,
         "description":"Known for his wit and wisdom, former U.S. Poet Laureate Billy Collins is one of America’s most beloved contemporary poets. In his MasterClass, Billy teaches you to appreciate the emotional pull of poetry. Learn his approach to exploring subjects, incorporating humor, and finding your voice. Discover the profound in the everyday, and let poetry lead you to the unexpected.",
         "status":"available",
         "instructor_name":"Billy Collins",
         "objectID":"100"
      },
      {
         "id":10,
         "class_name":"Aaron Sorkin Teaches Screenwriting",
         "instructor":"Aaron Sorkin",
         "headline":"Teaches Screenwriting",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/285/original/1466552319-AS_Headshot_V1_B.jpg?1466552319",
         "class slug":"aaron-sorkin-teaches-screenwriting",
         "url":"/classes/aaron-sorkin-teaches-screenwriting",
         "category":"Film & TV",
         "trailer_slug":"ciim4lsleo",
         "description":"Aaron Sorkin wrote his first movie on cocktail napkins. Those napkins turned into <span style=\"font-style:italic\">A Few Good Men</span>, starring Jack Nicholson. Now, the Academy Award winning writer of <span style=\"font-style:italic\">The West Wing</span> and <span style=\"font-style:italic\">The Social Network</span> is teaching screenwriting. You’ll learn his rules of storytelling, dialogue, character development, and what makes a script actually sell. By the end, you'll write unforgettable screenplays.",
         "status":"available",
         "objectID":"10"
      },
      {
         "id":1,
         "class_name":"James Patterson Teaches Writing",
         "instructor":"James Patterson",
         "headline":"Teaches Writing",
         "headshot":"https://d3e9iqx18mbphw.cloudfront.net/images/1479/original/1520560884-jp.jpg?1520560884",
         "class slug":"james-patterson-teaches-writing",
         "url":"/classes/james-patterson-teaches-writing",
         "category":"Writing",
         "trailer_slug":"gq5mjtyn9f",
         "description":"James Patterson, the author of 19 consecutive No. 1 New York Times bestsellers, reveals his tricks of the trade for the very first time. In this course, he guides you through every part of the book writing process.",
         "status":"available",
         "objectID":"1"
      }
   ],
   "nbHits":63,
   "page":0,
   "nbPages":1,
   "hitsPerPage":1000,
   "processingTimeMS":1,
   "query":"",
   "params":""
}
 *  */

/**
 * {
   "description":null,
   "poster_sources":[  ],
   "tags":[
      "ambient",
      "ch"
   ],
   "cue_points":[

   ],
   "custom_fields":{

   },
   "account_id":"5344802162001",
   "sources":[
      {
         "avg_bitrate":457000,
         "width":480,
         "duration":12245,
         "size":702447,
         "stream_name":"mp4:5344802162001/5344802162001_5800911540001_5800907168001.mp4?__nn__=1497926354001&slist=5344802162001/&auth=daEb8dachdXdgcOdgafdjbIdUc.b.dEdAbR-bDd9Pa-hca-koxCysAz_AAAs_FFEz_GsD&aifp=bcosuds",
         "codec":"H264",
         "asset_id":"5800911540001",
         "container":"MP4",
         "height":270,
         "app_name":"rtmp://cp150446.edgefcs.net/ondemand"
      },
      {
         "avg_bitrate":457000,
         "width":480,
         "src":"http://f1.media.brightcove.com/12/5344802162001/5344802162001_5800911540001_5800907168001.mp4?pubId=5344802162001&videoId=5800907168001",
         "size":702447,
         "height":270,
         "duration":12245,
         "container":"MP4",
         "codec":"H264",
         "asset_id":"5800911540001"
      },
      {
         "avg_bitrate":457000,
         "width":480,
         "src":"https://f1.media.brightcove.com/12/5344802162001/5344802162001_5800911540001_5800907168001.mp4?pubId=5344802162001&videoId=5800907168001",
         "size":702447,
         "height":270,
         "duration":12245,
         "container":"MP4",
         "codec":"H264",
         "asset_id":"5800911540001"
      },
      {
         "avg_bitrate":907000,
         "width":640,
         "duration":12245,
         "size":1388515,
         "stream_name":"mp4:5344802162001/5344802162001_5800911699001_5800907168001.mp4?__nn__=1497926354001&slist=5344802162001/&auth=daEb8dachdXdgcOdgafdjbIdUc.b.dEdAbR-bDd9Pa-hca-koxCysAz_AAAs_FFEz_GsD&aifp=bcosuds",
         "codec":"H264",
         "asset_id":"5800911699001",
         "container":"MP4",
         "height":360,
         "app_name":"rtmp://cp150446.edgefcs.net/ondemand"
      },
      {
         "avg_bitrate":907000,
         "width":640,
         "src":"http://f1.media.brightcove.com/12/5344802162001/5344802162001_5800911699001_5800907168001.mp4?pubId=5344802162001&videoId=5800907168001",
         "size":1388515,
         "height":360,
         "duration":12245,
         "container":"MP4",
         "codec":"H264",
         "asset_id":"5800911699001"
      },
      {
         "avg_bitrate":907000,
         "width":640,
         "src":"https://f1.media.brightcove.com/12/5344802162001/5344802162001_5800911699001_5800907168001.mp4?pubId=5344802162001&videoId=5800907168001",
         "size":1388515,
         "height":360,
         "duration":12245,
         "container":"MP4",
         "codec":"H264",
         "asset_id":"5800911699001"
      },
      {
         "avg_bitrate":1708000,
         "width":960,
         "duration":12245,
         "size":2607601,
         "stream_name":"mp4:5344802162001/5344802162001_5800913106001_5800907168001.mp4?__nn__=1497926354001&slist=5344802162001/&auth=daEb8dachdXdgcOdgafdjbIdUc.b.dEdAbR-bDd9Pa-hca-koxCysAz_AAAs_FFEz_GsD&aifp=bcosuds",
         "codec":"H264",
         "asset_id":"5800913106001",
         "container":"MP4",
         "height":540,
         "app_name":"rtmp://cp150446.edgefcs.net/ondemand"
      },
      {
         "avg_bitrate":1708000,
         "width":960,
         "src":"http://f1.media.brightcove.com/12/5344802162001/5344802162001_5800913106001_5800907168001.mp4?pubId=5344802162001&videoId=5800907168001",
         "size":2607601,
         "height":540,
         "duration":12245,
         "container":"MP4",
         "codec":"H264",
         "asset_id":"5800913106001"
      },
      {
         "avg_bitrate":1708000,
         "width":960,
         "src":"https://f1.media.brightcove.com/12/5344802162001/5344802162001_5800913106001_5800907168001.mp4?pubId=5344802162001&videoId=5800907168001",
         "size":2607601,
         "height":540,
         "duration":12245,
         "container":"MP4",
         "codec":"H264",
         "asset_id":"5800913106001"
      },
      {
         "type":"application/x-mpegURL",
         "src":"http://c.brightcove.com/services/mobile/streaming/index/master.m3u8?videoId=5800907168001&pubId=5344802162001",
         "container":"M2TS",
         "codec":"H264"
      },
      {
         "type":"application/x-mpegURL",
         "src":"https://secure.brightcove.com/services/mobile/streaming/index/master.m3u8?videoId=5800907168001&pubId=5344802162001&secure=true",
         "container":"M2TS",
         "codec":"H264"
      }
   ],
   "name":"CH_AmbientVideo_Brightcove_v4",
   "reference_id":null,
   "long_description":null,
   "duration":12245,
   "economics":"AD_SUPPORTED",
   "published_at":"2018-06-22T21:31:30.542Z",
   "text_tracks":[  ],
   "updated_at":"2018-06-22T21:35:07.501Z",
   "thumbnail":"http://brightcove04.o.brightcove.com/5344802162001/5344802162001_5800911696001_5800907168001-th.jpg?pubId=5344802162001&videoId=5800907168001",
   "poster":"http://brightcove04.o.brightcove.com/5344802162001/5344802162001_5800911533001_5800907168001-vs.jpg?pubId=5344802162001&videoId=5800907168001",
   "offline_enabled":false,
   "link":null,
   "id":"5800907168001",
   "ad_keys":null,
   "thumbnail_sources":[
      {
         "src":"http://brightcove04.o.brightcove.com/5344802162001/5344802162001_5800911696001_5800907168001-th.jpg?pubId=5344802162001&videoId=5800907168001"
      },
      {
         "src":"https://brightcove04pmdo-a.akamaihd.net/5344802162001/5344802162001_5800911696001_5800907168001-th.jpg?pubId=5344802162001&videoId=5800907168001"
      }
   ],
   "created_at":"2018-06-22T21:31:30.542Z"
}
 *  */
